### ISSUE TITLE
多个接口问题

### ISSUE THREAD

**Issue by maxiaoyi** [wzgiceman/RxjavaRetrofitDemo-string-master#2]
项目中有上百个接口，就需要写对应多个像SubjectPostApi这样的类，是不是有点臃肿了？我修改了用反射的方法去做，请求时只用这一个类即可，但是感觉不太好，有没有其他方法去优化？

**Comment by wzgiceman** [comment]
个人经验，一个api对应一个请求类，看似好像臃肿，但是目的是为了后续文档和项目的可读性！这块的逻辑可以自由扩展，我推荐是各个api独立，有利于代码的逻辑清晰度。  
建议：如果一定要修改，可以考虑用dagger优化你的这种情况
